Service filter
coopify/coopify pull request #12
Opened 2019-04-06 18:26 UTC by CamiloNicolasMartinez

2019-04-06 20:51 UTC, agustico13 approved these changes

2019-04-07 15:23 UTC, ismaelpuricelli approved these changes
Good work!

2019-04-07 15:44 UTC, juan17rodriguez requested changes

2019-04-07 15:44 UTC, juan17rodriguez commented on src/server/controllers/offers.ts
> +        const parsedexchangeInstances: string[] = JSON.parse(exchangeInstances)
Could be parsedExchangeInstances instead of parsedexchangeInstances?

2019-04-07 15:44 UTC, juan17rodriguez commented on src/server/models/sequelize/offer.ts
> +        if (filter.lowerPrice) { where.offerPrice.price = { $lt: filter.lowerPrice } }
Check if it corresponds

2019-04-07 16:17 UTC, juan17rodriguez approved these changes

2019-04-07 16:18 UTC, merged