Message tests
coopify/coopify pull request #31
Opened 2019-06-01 20:48 UTC by juan17rodriguez

2019-06-01 21:03 UTC, CamiloNicolasMartinez commented on test/server/controllers/messages.test.ts
> +            it.only('Should send the message to the conversation', async () => {
Quitar los `.only`

2019-06-02 15:47 UTC, CamiloNicolasMartinez approved these changes

2019-06-02 15:58 UTC, agustico13 approved these changes

2019-06-02 16:02 UTC, ismaelpuricelli approved these changes
Good work!

2019-06-02 16:02 UTC, CamiloNicolasMartinez requested changes

2019-06-02 16:02 UTC, CamiloNicolasMartinez commented on test/server/controllers/messages.test.ts
> +            })
Falta probar el caso donde intentas hacer un post a una conversación donde no estas incluido

2019-06-02 16:02 UTC, CamiloNicolasMartinez commented on test/server/controllers/messages.test.ts
> +        })
Falta probar el caso donde no pasas texto o pasas como texto el string vacío

2019-06-05 03:14 UTC, CamiloNicolasMartinez approved these changes

2019-06-06 01:40 UTC, merged